main/urls.py
#
# Copyright (c) 2019- Representable Team (Theodor Marcu, Lauren Johnston, Somya Arora, Kyle Barnes, Preeti Iyer).
#
# This file is part of Representable
# (see http://representable.org).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
from django.urls import include, path

from main.views import main, partners, dashboard, drives
from main.views.dashboard import AllowListUpdate, AllowListManage, AllowListDelete
from representable.settings.base import MAPBOX_KEY

app_name = "main"
urlpatterns = [
    
    path(
        "accounts/login/",
        main.RepresentableLoginView.as_view(),
        name="account_login",
    ),
    path(
        "accounts/signup/",
        main.RepresentableSignupView.as_view(),
        name="account_signup",
    ),

    # google code comment
    # path(
    #     "accounts/social/signup/",
    #     views.main.RepresentableSocialSignupView.as_view(),
    #     name="socialaccount_signup",
    # ),

    path(
        'block_group_polygons/<str:abbr>/',
        main.block_group_polygons,
        name='block_group_polygons',
    ),
    path("", main.Index.as_view(), name="index"),
    path(
        "entry_preview/",
        main.StateSelection.as_view(),
        name="entry_preview",
    ),
    path(
        "state_selection/",
        main.StateSelection.as_view(),
        name="state_selection",
    ),
    path(
        "state_selection/map",
        main.StateSelection.as_view(),
        name="state_selection_map",
    ),
    path(
        "entry/",
        main.EntryView.as_view(),
        {"token": "", "drive": ""},
        name="entry",
    ),
    path(
        "entry/drive/<slug:drive>/",
        main.EntryView.as_view(),
        {"token": "", "abbr": ""},
        name="entry",  # deprecated? every drive page should redirect to incl. abbr
    ),
    path(
        "entry/drive/<slug:drive>/<abbr>",
        main.EntryView.as_view(),
        {"token": ""},
        name="entry",
    ),
    path(
        "entry/c/<slug:drive>/",
        main.EntryView.as_view(),
        {"token": ""},
        name="entry_legacy",  # for old links
    ),
    path(
        "entry/t/<token>/",
        main.EntryView.as_view(),
        {"drive": ""},
        name="entry",
    ),
    path(
        "entry/t/<token>/<abbr>/",
        main.EntryView.as_view(),
        {"drive": ""},
        name="entry",
    ),
    path(
        "entry/<abbr>/",
        main.EntryView.as_view(),
        {"token": "", "state": "", "drive": ""},
        name="entry",
    ),
    path("about/", main.About.as_view(), name="about"),
    path("faq/", main.FAQ.as_view(), name="faq"),
    path("glossary/", main.Glossary.as_view(), name="glossary"),
    path("resources/", main.Resources.as_view(), name="resources"),
    path("resources/<abbr>/", main.Resources.as_view(), {"state": ""}, name="resources"),
    path("review/", main.Review.as_view(), name="review"),
    path("privacy/", main.Privacy.as_view(), name="privacy"),
    path("terms/", main.Terms.as_view(), name="terms"),
    path("state/<abbr>/", main.StatePage.as_view(), name="state"),
    path(
        "submission/<map_id>",
        main.Submission.as_view(),
        {"slug": "", "drive": ""},
        name="submission",
    ),
    path(
        "submission/<map_id>/<abbr>",
        main.Submission.as_view(),
        {"slug": "", "drive": ""},
        name="submission",
    ),
    path(
        "submission/thanks/<map_id>/<abbr>",
        main.Submission.as_view(),
        {"slug": "", "drive": ""},
        name="submission_thanks",
    ),
    path(
        "submission/thanks/drive/<slug:slug>/<slug:drive>/<map_id>",
        main.Submission.as_view(),
        name="submission_thanks",
    ),
    # path("blog/", views.main.Blog.as_view(), name="blog"),
    path("export/geojson/", main.ExportView.as_view(), name="export"),
    path("export/csv/", main.ExportView.as_view(), name="export"),
    path("export/geojson/<abbr>/", main.ExportView.as_view(), name="export"),
    path("export/csv/<abbr>/", main.ExportView.as_view(), name="export"),
    path(
        "multiexport/<abbr>/<type>/",
        main.MultiExportView.as_view(),
        name="multi_export",
    ),
    path(
        "multiexport/drive/<drive>/<type>/",
        partners.MultiExportView.as_view(),
        name="multi_export",
    ),
    path(
        "multiexport/org/<org>/<type>/",
        partners.MultiExportView.as_view(),
        name="multi_export",
    ),
    path("partners/", partners.IndexView.as_view(), name="partner_list"),
    path(
        "partners/welcome/",
        partners.WelcomeView.as_view(),
        name="partner_welcome",
    ),
    path(
        "partners/<slug:slug>/",
        partners.PartnerView.as_view(),
        name="partner_page",
    ),
    path("map/<state>/", main.Map.as_view(), name="map"),
    path("map/<state>/<lat>/<lng>", main.Map.as_view(), name="map"),
    path(
        "map/p/<slug:slug>/",
        partners.PartnerMap.as_view(),
        {"drive": ""},
        name="partner_map",
    ),
    path(
        "map/p/<slug:slug>/<slug:drive>/",
        partners.PartnerMap.as_view(),
        name="partner_map",
    ),
    path(
        "report/",
        partners.ReportView.as_view(),
        name="report_community",
    ),
    path(
        "drive/<slug:slug>/",
        drives.DriveView.as_view(),
        name="drive_page",
    ),
    # keeping this for now to maintain link to user testing campaign
    path(
        "c/<slug:slug>/",
        drives.DriveView.as_view(),
        name="drive_page_legacy",
    ),
    path("dashboard/", dashboard.IndexView.as_view(), name="dashboard"),
    path(
        "dashboard/entries/<int:pk>",
        dashboard.ViewEntry.as_view(),
        name="dash_entry_list",
    ),
    path(
        "dashboard/entries/<int:pk>",
        dashboard.ViewEntry.as_view(),
        name="dash_view_entry",
    ),
    path(
        "dashboard/entries/<int:pk>/delete/",
        dashboard.DeleteEntry.as_view(),
        name="dash_delete_entry",
    ),
    path(
        "dashboard/partners/create/",
        dashboard.CreateOrg.as_view(),
        name="create_org",
    ),
    path(
        "dashboard/partners/<slug:slug>-<int:pk>/",
        include(
            [
                path("", dashboard.HomeOrg.as_view(), name="home_org"),
                path(
                    "thanks/",
                    dashboard.ThanksOrg.as_view(),
                    name="thanks_org",
                ),
                path(
                    "edit/", dashboard.EditOrg.as_view(), name="edit_org"
                ),
                path(
                    "delete/",
                    dashboard.DeleteOrg.as_view(),
                    name="delete_org",
                ),
                path(
                    "members/",
                    dashboard.ManageOrg.as_view(),
                    name="manage_org",
                ),
                path(
                    "members/create",
                    dashboard.CreateMember.as_view(),
                    name="create_member",
                ),
                path(
                    "drives/create/",
                    dashboard.CreateDrive.as_view(),
                    name="create_drive",
                ),
                path(
                    "drives/<uuid:cam_pk>/",
                    dashboard.DriveHome.as_view(),
                    name="drive_home",
                ),
                path(
                    "drives/<uuid:cam_pk>/edit/",
                    dashboard.UpdateDrive.as_view(),
                    name="update_drive",
                ),
                path(
                    "drives/<uuid:cam_pk>/delete/",
                    dashboard.DeleteDrive.as_view(),
                    name="delete_drive",
                ),
                path(
                    "drives/<uuid:cam_pk>/upload-allowlist/",
                    AllowListUpdate.as_view(),
                    name="upload_allowlist",
                ),
                path(
                    "drives/<uuid:cam_pk>/manage-allowlist/",
                    AllowListManage.as_view(),
                    name="manage_allowlist",
                ),
                path(
                    "drives/<uuid:cam_pk>/manage-allowlist/delete/",
                    AllowListDelete.as_view(),
                    name="delete_allowlist",
                ),
            ]
        ),
    ),
]

main/views/drives.py
from ..models import (
    Drive,
    State,
    # Image
)
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

# from django.views.generic.detail import SingleObjectMixin
from django.views.generic import (
    ListView,
    DetailView,
)

# from django.shortcuts import render
# # from ..forms import ImageForm

class IndexView(ListView):
    model = Drive
    template_name = "main/drives/index.html"
    pk_url_kwarg = "cam_pk"


class DriveView(DetailView):
    model = Drive
    template_name = "main/drives/page.html"
    pk_url_kwarg = "cam_pk"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Get Drive State object
        drive_slug = self.kwargs["slug"]
        drive = Drive.objects.get(slug=drive_slug)
        if (State.objects.filter(abbr=drive.state)):
            context["state"] = State.objects.filter(abbr=drive.state)[0]
            context["page_type"] = "drive-page"
        return context


# def showimage(request):
#     lastimage= Image.objects.last()
#     imagefile= lastimage.imagefile

#     form= ImageForm(request.POST or None, request.FILES or None)
#     if form.is_valid():
#         form.save()
  
#     context= {'imagefile': imagefile,
#               'form': form
#               }   
      
#     return render(request, 'Blog/images.html', context)

main/templates/main/dashboard/partners/allowlist_manage.html
{% extends 'main/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
  <div class="row pt-3">
    <div class="col">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Home</a></li>
          <li class="breadcrumb-item"><a href="{% url 'main:dashboard' %}">Dashboard</a></li>
          <li class="breadcrumb-item"><a href="{% url 'main:home_org' object.organization.slug  object.organization.pk %}">Partners / {{ object.organization.name }}</a></li>
          <li class="breadcrumb-item"><a href="{% url 'main:drive_home' object.organization.slug object.organization.pk object.pk %}">Drives / {{ object.name }} </a></li>
          <li class="breadcrumb-item active" aria-current="page"> Manage Invite List</li>

        </ol>
      </nav>
    </div>
  </div>
  <div class="row pt-3">
    <div class="col-sm">
      <div class="card shadow-sm h-100">
        <div class="card-body">
          <h5>
            Invite List for {{ object.name }}
          </h5>
          <hr>
          <div>
          Invitations will automatically be sent to emails you add to this list.
          </div>
          <br>
            <div class="card shadow-sm">
            <div class="card-body">
                <h5><span class="badge badge-secondary"><i class="fas fa-file-upload"></i></span> Upload Email List </h5>
                <p> Upload a csv of emails to add them all to your list, or add individually below. <p>
                <a class="btn btn-primary float-right" href="{% url 'main:upload_allowlist' object.organization.slug  object.organization.pk object.pk %}" role="button">Upload <i class="fa fa-arrow-circle-right"></i></a>
            </div>
            </div>
            

        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm">
      <div class="card shadow-sm my-3">
        <div class="card-body">
          <h5> Invitees </h5>
          <div class="container">
            <div class="row">
              <div class="col-md">
                <form role="form" id="EmailAllowList" method="post">{% csrf_token %}
                  <div style="display: inline-block;">
                      <input style="height:36px" type="text" id="email" value="" name="email" placeholder="Add a member"/>
                      <button id="save" form="EmailAllowList" type="submit" class="btn btn-primary mb-1" value="Submit">Add</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <table class="table table-hover">

          {% for l in list %}
          <tr>

          <td> {{l.email}} </td>

          <td>
            {% comment %} {% if is_org_admin %}
              <button class="btn btn-danger float-right" data-toggle="modal" data-target="#deleteInvitee">
                <i class="fas fa-trash"></i>
              </button>
            {% endif %} {% endcomment %}
            <button class="btn btn-danger float-right" id="remove" data-toggle="modal" data-alid={{l.id}} data-target="#deleteInvitee">
            <i class="fas fa-trash"></i>
            </button>
          </td>

          </tr>
          {% endfor %}

          </table>

        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteInvitee" tabindex="-1" role="dialog" aria-labelledby="deleteInviteeLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to remove this member from your drive?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        This member will no longer be able to submit communities to your drive.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form role="form" id="deleteInviteeInfo" method="post" action="delete\">{% csrf_token %}
          <input type="text" class="hidden" name="alid" id="alid" value=""/>
          <button type="submit" class="btn btn-danger" name="Delete">Remove member</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block script %}

    <script>
    $(document).on("click", "#remove", function () {
         var alid = $(this).data('alid');
         $(".modal-footer #alid").val( alid );
    });
    </script>

{% endblock %}

main/templates/main/dashboard/partners/allowlist_upload.html
{% extends 'main/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">
                        Upload an Email List
                      </h5>
                      <form role="form" id="EmailAllowlist" method="post" enctype="multipart/form-data">{% csrf_token %}

                          <div class="form-group">
                        {% for field in form %}
                          <div class="fieldWrapper">
                              {{ field.errors }}
                              {{ field|append_attr:"class:form-control" }}
                              {% if field.help_text %}
                              <p class="help">{{ field.help_text|safe }}</p>
                              {% endif %}
                              <input type="file" value="Select file" name="file"/>
                          </div>
                      {% endfor %}

                      </div>
                      <div style="display: inline-block;">
                          <button id="save" form="EmailAllowlist" type="submit" class="btn btn-primary" value="Update">Submit</button>
                      </div>
                      </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/dashboard/partners/index.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="container-fluid px-1 px-lg-5 py-3 light-blue-bg">
  <div class="col-sm">
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <div class="alert alert-success">
          <strong>{% trans "Admin email added!" %}</strong>
        </div>
        {% endif %}
      {% endfor %}
    </ul>
    {% endif %}
  </div>
  <div class="row mt-1">
    <div class="col-12 col-lg-5 col-xl-4">
      <div class="card border-0 shadow-sm">
        <div class="card-body">
          <div class="row">
            <div class="col-0"></div> <!-- for the organization image -->
            <div class="col-6 order-first">
              <div class="row">
                <div class="col-12">
                  <h5>{{ object.name}}
                  {% if object.verified %}
                  <img class="ml-1 pb-1 img-fluid verified-logo" src="{% static 'img/verified.svg' %}" alt="verified check mark"></img>
                  {% endif %}
                  </h5>
                </div>
                <div class="col-12">
                  <p> <span class="strong text-5996D2">{% trans "States" %}:
                    {% for state in object.states %}
                    <span class="badge badge-secondary">{{state}}</span>
                    {% endfor %}
                  </p>
                </div>
              </div>
            </div>
            <div class="col-3"></div>
            <div class="col-3">
              {% if is_org_admin %}
              <button class="btn btn-danger float-right" data-toggle="modal" data-target="#deleteOrgConfirm">
                <i class="fas fa-trash"></i>
              </button>
              {% endif %}
            </div>

          </div>
          {% comment %} {% if is_org_admin %}
          <button class="btn btn-danger float-right mt-4" data-toggle="modal" data-target="#deleteOrgConfirm">
            <i class="fas fa-trash"></i>
          </button>
          {% endif %} {% endcomment %}
          <p class="scrollable"><span class="text-5996D2">{% trans "Description" %}:</span> {{ object.description }} </p>

          <div class="row">
            <div class="col-6">
              <a href="{% url 'main:edit_org' object.slug  object.pk %}" class="btn btn-sm btn-outline-primary w-100 btn-ls-md" role="button">{% trans "EDIT DETAILS" %}</a>
            </div>
            <div class="col-6 text-right">
              <a href="{% url 'main:manage_org' object.slug  object.pk %}" class="btn btn-sm btn-outline-primary w-100 btn-ls-md" role="button">{% trans "ADD ADMINS" %}</a>
            </div>
          </div>

        </div>
      </div>
    </div>
    <div class="col-12 col-lg-7 col-xl-8 pt-3 pt-xl-0">
      <div class="card border-0 shadow-sm h-100">
        <div class="card-body h-100">
          <h5>
            {% trans "Community Mapping Drives" %}
          </h5>
          <div class="row">
            <div class="col-12">
              {% if drives %}
              <ul class="list-group org-dash-drive-group scrollable my-3 mb-5">
                {% for drive in drives %}
                <li class="border-0 light-blue-bg list-group-item d-flex justify-content-between align-items-center mb-4">
                  {{ drive.name }}
                  <a class="btn btn-outline-primary border-0" href="{% url 'main:drive_home' object.slug  object.pk drive.id %}" role="button">{% trans "Manage" %}</a>
                </li>
                {% endfor %}
              </ul>
              {% else %}
              <p class="my-3">{% blocktrans %}You haven't created any community mapping drives for this organization.
                a new one below to start collecting data.{% endblocktrans %}</p>
              {% endif %}
            </div>
          </div>

          <div class="text-center pt-3 org-card-btn">
            <a class="btn btn-outline-primary btn-ls-md" href="{% url 'main:create_drive' object.slug  object.pk %}" role="button">{% trans "CREATE NEW" %}</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row pb-3">
    <div class="col-12 col-md-4">
      <div class="card h-100 border-0 shadow-sm my-3 pb-3">
        <div class="card-body h-100">
          <h6 class="text-2A94F4 text-xl-center">
            <strong>{% trans "1. Download the Representable Toolkit" %}</strong>
          </h6>
          <div class="row">
            <div class="d-none d-xl-block col-xl-2 pt-xl-1 text-right">
              <i class="fas fa-toolbox org-icon text-2A94F4"></i>
            </div>
            <div class="col-12 col-xl-10 pl-xl-2">
              {% trans "Check out our toolkit to help guide you through the process of collecting maps." %}
            </div>
          </div>
          <div class="text-center pt-3 org-card-btn">
            <a class="btn btn-primary btn-ls-md" target="_blank" href="https://drive.google.com/file/d/1NHkU_SazAHgF2rv7-9we13rsBonv8s5S/view?usp=sharing" role="button">{% trans "VIEW & DOWNLOAD" %}</a>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-4 pt-2 pt-xl-0">
      <div class="card h-100 border-0 shadow-sm my-3 pb-3">
        <div class="card-body h-100">
          <h6 class="text-2A94F4 text-xl-center">
            <strong>{% trans "2. Create a Community Mapping Drive" %}</strong>
          </h6>
          <div class="row">
            <div class="d-none d-xl-block col-xl-2 pt-xl-1 text-right">
              <i class="fas fa-home org-icon text-2A94F4"></i>
            </div>
            <div class="col-12 col-xl-10 pl-xl-2">
              {% trans "Create a drive to collect community maps from your members. You can make multiple community mapping drives." %}
            </div>
          </div>
          <div class="text-center pt-3 org-card-btn">
            <a class="btn btn-primary btn-ls-md" href="{% url 'main:create_drive' object.slug  object.pk %}" role="button">{% trans "CREATE NEW DRIVE" %}</a>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-4 pt-2 pt-xl-0">
      <div class="card h-100 border-0 shadow-sm my-3 pb-3">
        <div class="card-body h-100">
          <h6 class="text-2A94F4 text-xl-center">
            <strong>{% trans "3. View and Share your Maps" %}</strong>
          </h6>
          <div class="row">
            <div class="d-none d-xl-block col-xl-2 pt-xl-1 text-right">
              <i class="fas fa-share-square org-icon text-2A94F4"></i>
            </div>
            <div class="col-12 col-xl-10 pl-xl-2">
              {% trans "Use this link to share all maps collected by your organization (includes all drives)" %}: <a href="{% url 'main:partner_map' object.slug %}">https://representable.org{% url 'main:partner_map' object.slug %}</a>
            </div>
          </div>
          <div class="text-center pt-3 org-card-btn">
            <a class="btn btn-primary btn-ls-md" href="{% url 'main:partner_map' object.slug %}" role="button">{% trans "VIEW ALL MAPS" %}</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteOrgConfirm" tabindex="-1" role="dialog" aria-labelledby="deleteOrgLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{% trans "Are you sure you want to delete this organization?" %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% blocktrans trimmed %}
        This action cannot be undone. All organization information will be permanently deleted. All drives associated with this organization
        will be permanently deleted. Communities submitted through these drives will not be deleted, but will no longer be associated with the drive
        or your organization.
        {% endblocktrans %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Cancel" %}</button>
        <form role="form" id="deleteOrgInfo" method="post" action="delete\">{% csrf_token %}
          {% comment %} <input type="hidden" name="drive_slug" value="{{ object.slug }}"> {% endcomment %}
          <button type="submit" class="btn btn-danger" name="Delete">{% trans "Delete organization permanently" %}</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

main/templates/main/dashboard/partners/member_form.html
{% extends 'main/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %}
{{ form.media.css }}
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">
                        Add Admins
                      </h5>
                      <form role="form" id="CreateMember" method="post">{% csrf_token %}

                          <div class="form-group">
                        {% for field in form %}
                          <div class="fieldWrapper">
                            {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                            {% endif %}
                              {{ field.errors }}
                              {{ field.label_tag }} {{ field }}
                              {% if field.help_text %}
                              <p class="help">{{ field.help_text|safe }}</p>
                              {% endif %}
                          </div>
                      {% endfor %}
                      </div>
                      <div style="display: inline-block;">
                          <button id="save" form="CreateMember" type="submit" class="btn btn-primary" value="Submit">Submit</button>
                      </div>
                      </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block script %}
{{ form.media.js }}
{% endblock %}

main/templates/main/dashboard/partners/membership.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row pt-3">
    <div class="col">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Home</a></li>
          <li class="breadcrumb-item"><a href="{% url 'main:dashboard' %}">Dashboard</a></li>
          <li class="breadcrumb-item"><a href="{% url 'main:home_org' view.kwargs.slug view.kwargs.pk %}">Partners / {{ organization.name }}</a></li>
          <li class="breadcrumb-item active" aria-current="page"> Membership</li>
        </ol>
      </nav>
    </div>
  </div>
  <div class="row pt-2">
    <div class="col">
      <h4>
        Manage Users
      </h4>
      <hr>
      <div class="alert alert-primary" role="alert">
        Need to add administrators? Add them <a href="{% url 'main:create_member' view.kwargs.slug view.kwargs.pk %}" class="alert-link">here</a>.
      </div>
    </div>
  </div>
  <div class="row pt-3">
    <div class="col-sm mb-5">
      <div class="card shadow-sm h-100">
        <div class="card-body">
          <table class="table table-striped">
            <thead>
              <tr>
                {% for k in header %}
                <th>{{k}}</th>
                {% endfor %}
              </tr>
            </thead>
            <tbody>
              {% for member in members %}
              <tr>
                <td>{{member.member.username}}</td>
                 {% if member.is_org_admin %}
                <td>Admin</td>

                {% else %}
                <td>Member</td>

                {% endif %}
                <td>{{member.date_joined}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main/templates/main/dashboard/partners/thanks.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}


{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h1 class="font-weight-light text-center border-bottom pb-3">
                      {% trans "Thank you for creating an organization!" %}

                      {% if not verified %}
                      <p> {% trans "Please verify your email." %} </p>
                      {% endif %}
                    </h1>
                    <div class="py-2">
                      <p class="text-center">{% trans "We are excited to work with you!" %}</p>
                      <p><span class="badge badge-primary">1</span> {% blocktrans trimmed %}Check out our <a href="https://docs.google.com/document/d/1NJMUpZodlqo96xVASJzihpcfgWir18ifMaMD380zrXE/edit">organization guide</a> to learn more about using Representable to gather community maps.{% endblocktrans %}</p>
                      <p><span class="badge badge-primary">2</span> {% blocktrans trimmed %}Contact us at <a href="mailto:team@representable.org"> team@representable.org</a> with any questions. {% endblocktrans %}</p>
                      <p><span class="badge badge-primary">3</span> {% blocktrans trimmed %}Click the button below to go to the Organization Dashboard and get started by creating a community mapping drive. {% endblocktrans %}</p>
                    </div>
                    {% if not verified %}
                    <p class = "text-center"> {% blocktrans trimmed %}Email verification will be necessary
                        to access certain organization features on Representable. We have resent an email verification link to your inbox.{% endblocktrans %}</p>
                    {% endif %}
                    <div class="text-center"> <a class="btn btn-primary btn-canvas font-weight-light text-uppercase" href="{% url 'main:home_org' view.kwargs.slug  view.kwargs.pk %}" role="button"><small>{% trans "organization dashboard" %}</small></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}