main/urls.py
#
# Copyright (c) 2019- Representable Team (Theodor Marcu, Lauren Johnston, Somya Arora, Kyle Barnes, Preeti Iyer).
#
# This file is part of Representable
# (see http://representable.org).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
from django.urls import include, path

from main.views import main, partners, dashboard, drives
from main.views.dashboard import AllowListUpdate, AllowListManage, AllowListDelete
from representable.settings.base import MAPBOX_KEY

app_name = "main"
urlpatterns = [
    
    path(
        "accounts/login/",
        main.RepresentableLoginView.as_view(),
        name="account_login",
    ),
    path(
        "accounts/signup/",
        main.RepresentableSignupView.as_view(),
        name="account_signup",
    ),

    # google code comment
    # path(
    #     "accounts/social/signup/",
    #     views.main.RepresentableSocialSignupView.as_view(),
    #     name="socialaccount_signup",
    # ),

    path(
        'block_group_polygons/<str:abbr>/',
        main.block_group_polygons,
        name='block_group_polygons',
    ),
    path("", main.Index.as_view(), name="index"),
    path(
        "entry_preview/",
        main.StateSelection.as_view(),
        name="entry_preview",
    ),
    path(
        "state_selection/",
        main.StateSelection.as_view(),
        name="state_selection",
    ),
    path(
        "state_selection/map",
        main.StateSelection.as_view(),
        name="state_selection_map",
    ),
    path(
        "entry/",
        main.EntryView.as_view(),
        {"token": "", "drive": ""},
        name="entry",
    ),
    path(
        "entry/drive/<slug:drive>/",
        main.EntryView.as_view(),
        {"token": "", "abbr": ""},
        name="entry",  # deprecated? every drive page should redirect to incl. abbr
    ),
    path(
        "entry/drive/<slug:drive>/<abbr>",
        main.EntryView.as_view(),
        {"token": ""},
        name="entry",
    ),
    path(
        "entry/c/<slug:drive>/",
        main.EntryView.as_view(),
        {"token": ""},
        name="entry_legacy",  # for old links
    ),
    path(
        "entry/t/<token>/",
        main.EntryView.as_view(),
        {"drive": ""},
        name="entry",
    ),
    path(
        "entry/t/<token>/<abbr>/",
        main.EntryView.as_view(),
        {"drive": ""},
        name="entry",
    ),
    path(
        "entry/<abbr>/",
        main.EntryView.as_view(),
        {"token": "", "state": "", "drive": ""},
        name="entry",
    ),
    path("about/", main.About.as_view(), name="about"),
    path("faq/", main.FAQ.as_view(), name="faq"),
    path("glossary/", main.Glossary.as_view(), name="glossary"),
    path("resources/", main.Resources.as_view(), name="resources"),
    path("resources/<abbr>/", main.Resources.as_view(), {"state": ""}, name="resources"),
    path("review/", main.Review.as_view(), name="review"),
    path("privacy/", main.Privacy.as_view(), name="privacy"),
    path("terms/", main.Terms.as_view(), name="terms"),
    path("state/<abbr>/", main.StatePage.as_view(), name="state"),
    path(
        "submission/<map_id>",
        main.Submission.as_view(),
        {"slug": "", "drive": ""},
        name="submission",
    ),
    path(
        "submission/<map_id>/<abbr>",
        main.Submission.as_view(),
        {"slug": "", "drive": ""},
        name="submission",
    ),
    path(
        "submission/thanks/<map_id>/<abbr>",
        main.Submission.as_view(),
        {"slug": "", "drive": ""},
        name="submission_thanks",
    ),
    path(
        "submission/thanks/drive/<slug:slug>/<slug:drive>/<map_id>",
        main.Submission.as_view(),
        name="submission_thanks",
    ),
    # path("blog/", views.main.Blog.as_view(), name="blog"),
    path("export/geojson/", main.ExportView.as_view(), name="export"),
    path("export/csv/", main.ExportView.as_view(), name="export"),
    path("export/geojson/<abbr>/", main.ExportView.as_view(), name="export"),
    path("export/csv/<abbr>/", main.ExportView.as_view(), name="export"),
    path(
        "multiexport/<abbr>/<type>/",
        main.MultiExportView.as_view(),
        name="multi_export",
    ),
    path(
        "multiexport/drive/<drive>/<type>/",
        partners.MultiExportView.as_view(),
        name="multi_export",
    ),
    path(
        "multiexport/org/<org>/<type>/",
        partners.MultiExportView.as_view(),
        name="multi_export",
    ),
    path("partners/", partners.IndexView.as_view(), name="partner_list"),
    path(
        "partners/welcome/",
        partners.WelcomeView.as_view(),
        name="partner_welcome",
    ),
    path(
        "partners/<slug:slug>/",
        partners.PartnerView.as_view(),
        name="partner_page",
    ),
    path("map/<state>/", main.Map.as_view(), name="map"),
    path("map/<state>/<lat>/<lng>", main.Map.as_view(), name="map"),
    path(
        "map/p/<slug:slug>/",
        partners.PartnerMap.as_view(),
        {"drive": ""},
        name="partner_map",
    ),
    path(
        "map/p/<slug:slug>/<slug:drive>/",
        partners.PartnerMap.as_view(),
        name="partner_map",
    ),
    path(
        "report/",
        partners.ReportView.as_view(),
        name="report_community",
    ),
    path(
        "drive/<slug:slug>/",
        drives.DriveView.as_view(),
        name="drive_page",
    ),
    # keeping this for now to maintain link to user testing campaign
    path(
        "c/<slug:slug>/",
        drives.DriveView.as_view(),
        name="drive_page_legacy",
    ),
    path("dashboard/", dashboard.IndexView.as_view(), name="dashboard"),
    path(
        "dashboard/entries/<int:pk>",
        dashboard.ViewEntry.as_view(),
        name="dash_entry_list",
    ),
    path(
        "dashboard/entries/<int:pk>",
        dashboard.ViewEntry.as_view(),
        name="dash_view_entry",
    ),
    path(
        "dashboard/entries/<int:pk>/delete/",
        dashboard.DeleteEntry.as_view(),
        name="dash_delete_entry",
    ),
    path(
        "dashboard/partners/create/",
        dashboard.CreateOrg.as_view(),
        name="create_org",
    ),
    path(
        "dashboard/partners/<slug:slug>-<int:pk>/",
        include(
            [
                path("", dashboard.HomeOrg.as_view(), name="home_org"),
                path(
                    "thanks/",
                    dashboard.ThanksOrg.as_view(),
                    name="thanks_org",
                ),
                path(
                    "edit/", dashboard.EditOrg.as_view(), name="edit_org"
                ),
                path(
                    "delete/",
                    dashboard.DeleteOrg.as_view(),
                    name="delete_org",
                ),
                path(
                    "members/",
                    dashboard.ManageOrg.as_view(),
                    name="manage_org",
                ),
                path(
                    "members/create",
                    dashboard.CreateMember.as_view(),
                    name="create_member",
                ),
                path(
                    "drives/create/",
                    dashboard.CreateDrive.as_view(),
                    name="create_drive",
                ),
                path(
                    "drives/<uuid:cam_pk>/",
                    dashboard.DriveHome.as_view(),
                    name="drive_home",
                ),
                path(
                    "drives/<uuid:cam_pk>/edit/",
                    dashboard.UpdateDrive.as_view(),
                    name="update_drive",
                ),
                path(
                    "drives/<uuid:cam_pk>/delete/",
                    dashboard.DeleteDrive.as_view(),
                    name="delete_drive",
                ),
                path(
                    "drives/<uuid:cam_pk>/upload-allowlist/",
                    AllowListUpdate.as_view(),
                    name="upload_allowlist",
                ),
                path(
                    "drives/<uuid:cam_pk>/manage-allowlist/",
                    AllowListManage.as_view(),
                    name="manage_allowlist",
                ),
                path(
                    "drives/<uuid:cam_pk>/manage-allowlist/delete/",
                    AllowListDelete.as_view(),
                    name="delete_allowlist",
                ),
            ]
        ),
    ),
]

main/views/drives.py
from ..models import (
    Drive,
    State,
    # Image
)
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

# from django.views.generic.detail import SingleObjectMixin
from django.views.generic import (
    ListView,
    DetailView,
)

# from django.shortcuts import render
# # from ..forms import ImageForm

class IndexView(ListView):
    model = Drive
    template_name = "main/drives/index.html"
    pk_url_kwarg = "cam_pk"


class DriveView(DetailView):
    model = Drive
    template_name = "main/drives/page.html"
    pk_url_kwarg = "cam_pk"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Get Drive State object
        drive_slug = self.kwargs["slug"]
        drive = Drive.objects.get(slug=drive_slug)
        if (State.objects.filter(abbr=drive.state)):
            context["state"] = State.objects.filter(abbr=drive.state)[0]
            context["page_type"] = "drive-page"
        return context


# def showimage(request):
#     lastimage= Image.objects.last()
#     imagefile= lastimage.imagefile

#     form= ImageForm(request.POST or None, request.FILES or None)
#     if form.is_valid():
#         form.save()
  
#     context= {'imagefile': imagefile,
#               'form': form
#               }   
      
#     return render(request, 'Blog/images.html', context)

main/templates/main/base.html
{% extends 'base.html' %}

main/templates/main/entry_privacy.html
{% load i18n %}
{% load widget_tweaks %}

<div class="entry-step row mb-2">
    <div class="col">
        Step 4
    </div>
</div>
<div class="row row-equal-cols">
    <div class="col">
        <div id="backup_error" class="alert alert-danger alert-dismissible fade show form-error d-none" role="alert">
            {% blocktrans trimmed %}
                <p id="backup_error_txt" class="p-0 m-0"></p>
            {% endblocktrans %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div id="need_privacy" class="alert alert-danger alert-dismissible fade show form-error d-none" role="alert">
            {% trans "Please make sure to agree to the terms and conditions." %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="row mx-auto">
            <h4>
                <strong class="header-text">
                {% trans "Privacy and Terms of Use" %}
                </strong>
            </h4>
        </div>

        <br>

        <p class="info-text">
            {% blocktrans trimmed %}We gather your identifying information to verify that you are a real person.
            We will not publicly share anyone's individual personal information, such as name, address, or email. Your privacy is our highest priority.
            {% endblocktrans %}
            {% if has_drive %}
            <br>
            We will only share your information with the organizers of {{organization_name}} because you are adding the community through their community mapping drive.
            {% endif %}
        </p>

        <div class="row row-equal-cols toc-check my-5">
            <div class="col d-none d-xl-block">
                <input class="toc-check-input" type="checkbox" value="" id="toc_check_xl" required="">
                <label class="toc-check-label info-text" for="toc_check_xl">
                    {% url 'main:privacy' as url1%}
                    {% url 'main:terms' as url2%}

                    {% blocktrans trimmed %}Click here to indicate that you have read and agree to the
                    <a target="_blank" rel="noopener noreferrer" href={{url2}}>Terms of Use</a> and
                    <a target="_blank" rel="noopener noreferrer" href="{{url1}}">Privacy Policy</a>.
                    {% endblocktrans %}
                    <small class="text-danger">*</small>
                </label>
            </div>

            <div class="col-1 mt-1 d-xl-none">
                <input class="toc-check-input" type="checkbox" value="" id="toc_check" required="">
            </div>
            <div class="col-9 p-md-0 d-xl-none">
                <label class="toc-check-label p-0 info-text" for="toc_check">
                    {% url 'main:privacy' as url1%}
                    {% url 'main:terms' as url2%}

                    {% blocktrans trimmed %}Click here to indicate that you have read and agree to the
                    <a target="_blank" rel="noopener noreferrer" href={{url2}}>Terms of Use</a> and
                    <a target="_blank" rel="noopener noreferrer" href="{{url1}}">Privacy Policy</a>.
                    {% endblocktrans %}
                    <small class="text-required">*</small>
                </label>
            </div>
        </div>

        <div class="row w-xl-50 mx-auto rounded" style="background-color: #DAEFFF;">
            <div class="m-4">
                <p><strong class="header-text">
                {% blocktrans trimmed %}
                    Submitted communities are final and public.
                {% endblocktrans %}
                </strong></p>

                <p class="info-text">
                    {% blocktrans trimmed %} In order to edit a saved community you will need
                    to create a new community and delete the old one. Your community map, name,
                    and testimony will be publicly visible on Representable.org {% endblocktrans %}
                </p>
            </div>
        </div>

        <div class="row pt-5">
            <div id="need_captcha" class="col-12 text-center w-xl-50 d-none">
                <div class="alert alert-danger alert-dismissible fade show form-error d-inline-block" role="alert">
                    {% trans "You need to complete the recaptcha to submit this map." %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
            <div class="col-12 text-center p-0"><div class="g-recaptcha pt-0 mr-4 mr-md-0" data-sitekey="{{recaptcha_public}}"></div></div>
        </div>

        <div class="row my-5 pb-2">
            <div class="col text-center">
                <button class="btn btn-lg btn-primary no-underline-link entry-nav-btn mr-3 mapping-icon btn-ls-md" onclick="privacyToMap()" type="button"><i class="fas fa-angle-left pr-2"></i>{% trans "BACK" %}</button>
                <button id="entrySubmissionButton" class="btn btn-lg btn-primary no-underline-link entry-nav-btn ml-4 mapping-icon btn-ls-md" type="submit" form="entryForm" value="Submit">{% trans "SUBMIT" %}</button>
            </div>
        </div>
    </div>
</div>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load leaflet_tags %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block head %}
{% leaflet_js %}
{% leaflet_css %}
<!--  Mapbox GL JS-->
<meta charset='utf-8' />
<meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
{% endblock %}

<!-- Main Content -->
{% block content %}
<div id="home-bg" class="container-fluid">
  <!-- Illustration -->
  <div class="row row-hero row-eq-height mt-sm-4 mx-0">
    <div class="col-12 mobile-padding-x mobile-padding-top text-center">
      <img class="w-62 align-bottom" src="{% static 'img/home-people.svg' %}" alt="people together holding shapes"> </img>
      <div class="text-center">
        <span id="home-mapping-am" class="d-block font-large-mobile font-weight-bold dark-blue-text">{% trans "MAPPING AMERICA" %}</span>
        <span class="d-block h1 btn-ls-md font-weight-light font-medium-mobile dark-blue-text">{% blocktrans trimmed %} One <b>community</b> at a time. {% endblocktrans %}</span>
      </div>
    </div>
  </div>
  <div class="row row-hero row-eq-height my-auto mx-0">
    <div class="col-12 text-center my-auto pt-3">
      <a id="get-started-btn" class="text-center font-medium-mobile btn btn-primary btn-lg py-3 font-weight-bold btn-ls-lg" href="{% url 'main:state_selection' %}"  role="button">{% trans "GET STARTED" %}</a>
    </div>
  </div>
  <div class="row">
    <h4 class="mx-auto gray-text my-2">-OR-</h4>
  </div>
  <div class="row row-hero row-eq-height my-auto mx-0">
    <div class="d-none d-md-block col-12 col-md-3"></div>
    <div class="d-none d-md-block col-12 col-md-6 text-center">
      <a class="font-medium-mobile btn btn-outline-secondary py-2 btn-ls-md mb-5 mr-2 mt-2 border-solid" style="border-radius: 0;" href="{% url 'main:state_selection_map' %}"  role="button">{% trans "VIEW & EXPORT MAPS" %}</a>
      <a class="font-medium-mobile btn btn-outline-secondary py-2 btn-ls-md mb-5 mt-2 border-solid" style="border-radius: 0;" href="{% url 'main:partner_welcome' %}"  role="button">{% trans "JOIN AS AN ORG" %}</a>
    </div>
    <div class="d-block d-md-none col-12 col-md-6 text-center">
      <a class="font-medium-mobile btn btn-outline-secondary py-2 btn-ls-md my-2 border-solid" style="border-radius: 0;" href="{% url 'main:state_selection_map' %}"  role="button">{% trans "VIEW & EXPORT MAPS" %}</a>
    </div>
    <div class="d-block d-md-none col-12 col-md-6 text-center">
      <a class="font-medium-mobile btn btn-outline-secondary py-2 btn-ls-md my-2 border-solid" style="border-radius: 0;" href="{% url 'main:partner_welcome' %}"  role="button">{% trans "JOIN AS AN ORG" %}</a>
    </div>
    <div class="d-none d-md-block col-12 col-md-3"></div>
  </div>
</div>
  <div class="container-fluid bg-white">
    <div class="container mb-5">
      <div class="row gray-text pt-5 px-md-5 mt-5">
        <div class="col-2">
          <img class="card-img-top img-fluid m-2 w-100 mx-auto mb-md-4 pt-3 pt-md-0" src="{% static 'img/home-shapes-1.svg' %}" alt="two light shapes"></img>
        </div>
        <div class="col-4 my-auto">
          <h1 class="font-medium-mobile font-weight-bold">{% blocktrans trimmed %} Describe <br>Your Community {% endblocktrans %}</h1>
          <h3 class="font-small-mobile font-weight-light">{% trans "by identifying shared interests and community needs." %}</h3>
        </div>
        <div class="col-2">
          <img class="card-img-top img-fluid m-2 w-100 mx-auto mb-md-4 pt-3 pt-md-0" src="{% static 'img/home-shapes-3.svg' %}" alt="two light shapes"></img>
        </div>
        <div class="col-4 my-auto">
          <h1 class="font-medium-mobile font-weight-bold">{% blocktrans trimmed %} Draw a <br> Community Map {% endblocktrans %}</h1>
          <h3 class="font-small-mobile font-weight-light">{% trans "by choosing units that make up your community." %}</h3>
        </div>
      </div>
      <div class="row gray-text pb-md-5">
        <div class="col-3"></div>
        <div class="col-2">
          <img class="card-img-top img-fluid m-2 w-100 mx-auto mb-md-4 pt-3 pt-md-0" src="{% static 'img/home-shapes-2.svg' %}" alt="two light shapes"></img>
        </div>
        <div class="col-4 my-auto">
          <h1 class="font-medium-mobile font-weight-bold">{% blocktrans trimmed %} Share <br>Your Map {% endblocktrans %}</h1>
          <h3 class="font-small-mobile font-weight-light">{% trans "as public input for map makers to use when drawing new voting districts." %}</h3>
        </div>
        <div class="col-3"></div>
      </div>
    </div>
  </div>
  <div class="row state-maps-bg d-none d-md-block m-0">
    <div class="container">
      <div class="row">
        <div class="col-1"></div>
        <div class="col-6 my-auto gray-text py-5">
          <h2 class="mb-3 font-weight-bold mt-4 mt-lg-2">We are mapping America.</h2>
          <h4>Check out the communities drawn in your state.</h4>
          <a class="btn font-weight-bold btn-outline-primary mt-3 btn-ls-md border-solid px-4 py-2 mb-4" href="{% url 'main:state_selection_map' %}">
              {% trans "VIEW COMMUNITIES" %}
          </a>
        </div>
        <div class="col-5">
          <!-- <img class="img-fluid align-bottom h-100" src="{% static 'img/map-preview.png' %}" alt="preview of Representable's map page"> </img> -->
        </div>
      </div>
    </div>
  </div>
  <!-- MOBILE ONLY -->
  <div class="container state-maps-bg d-block d-md-none mt-4">
    <div class="row">
      <h2 class="mb-3 font-weight-bold mt-4 mt-lg-2 mx-auto">We are mapping America.</h2>
      <h5 class="mx-5 px-4 text-center">Check out the communities drawn in your state.</h5>
      <a class="mx-auto btn btn-outline-primary font-weight-bold mt-3 btn-ls-md border-solid px-4 py-2 mb-4 mb-lg-2" href="{% url 'main:state_selection_map' %}">
          {% trans "VIEW COMMUNITIES" %}
      </a>
    </div>
  </div>
  <div class="container">
    <div class="container">
      <div class="row my-5 d-none d-md-flex">
        <div class="col-md-3">
          <img class="card-img-top img-fluid m-2 w-25 w-sm-100 mx-auto mb-md-4" src="{% static 'img/home-shapes-4.svg' %}" alt="two light shapes"></img>
        </div>
        <div class="col-md-6 gray-text px-3">
          <img class="mx-auto d-block w-21 py-5" src="{% static 'img/logo-gradient.svg' %}" alt="representable logo - continental USA made of blocks"> </img>
          <h5 class="pt-3 font-medium-mobile font-weight-light">{% blocktrans trimmed %}<b>Our mission is to give communities a voice in drawing voting districts.</b> Representable allows people to draw Communities of Interest and share information about the interests and needs in those communities.{% endblocktrans %}</h5>
          <h5 class="py-4 font-weight-light font-small-mobile mb-0">{% blocktrans trimmed %}<br><b>Gerrymandering is threatening democracy.</b> Politicians have been drawing voting districts that silence the voices of communities. This prevents communities from electing representatives that listen to their needs. Gathering Communities of Interest maps helps fight gerrymandering.{% endblocktrans %}</h5>
          <div class="text-center">
            <a class="btn btn-outline-primary mt-3 btn-ls-md border-solid px-3 mb-4 mb-lg-2" href="{% url 'main:resources' %}">
                {% trans "LEARN MORE" %}
            </a>
          </div>
        </div>
        <div class="col-md-3">
          <img class="card-img-top img-fluid m-2 w-25 w-sm-100 mx-auto mb-md-4" src="{% static 'img/home-shapes-5.svg' %}" alt="two light shapes"></img>
        </div>
      </div>
      <div class="row my-5 d-flex d-md-none">
        <div class="col-4">
          <img class="card-img-top img-fluid m-2 w-100 mx-auto mb-md-4" src="{% static 'img/home-shapes-4.svg' %}" alt="two light shapes"></img>
        </div>
        <div class="col-4">
          <img class="mx-auto d-block w-100 py-5" src="{% static 'img/logo-gradient.svg' %}" alt="representable logo - continental USA made of blocks"> </img>
        </div>
        <div class="col-4">
          <img class="card-img-top img-fluid m-2 w-100 mx-auto mb-md-4" src="{% static 'img/home-shapes-5.svg' %}" alt="two light shapes"></img>
        </div>
      </div>
      <div class="row my-5 d-flex d-md-none">
        <div class="col gray-text px-3">
          <h5 class="pt-3 font-medium-mobile font-weight-light">{% blocktrans trimmed %}<b>Our mission is to give communities a voice in drawing voting districts.</b> Representable allows people to draw Communities of Interest and share information about the interests and needs in those communities.{% endblocktrans %}</h5>
          <h5 class="py-4 font-weight-light font-small-mobile mb-0">{% blocktrans trimmed %}<br><b>Gerrymandering is threatening democracy.</b> Politicians have been drawing voting districts that silence the voices of communities. This prevents communities from electing representatives that listen to their needs. Gathering Communities of Interest maps helps fight gerrymandering.{% endblocktrans %}</h5>
          <div class="text-center">
            <a class="btn btn-outline-primary mt-3 btn-ls-md border-solid px-3 mb-4 mb-lg-2" href="{% url 'main:resources' %}">
                {% trans "LEARN MORE" %}
            </a>
          </div>
        </div>
      </div>
      <div class="row mt-5 mx-md-5 pb-5 px-5">
        <div class="col-md-4"></div>
        <div class="col-md-1 text-center py-2 py-md-0">
          <a href="https://www.facebook.com/Representable.org/" target="_blank"><img class="social-media-logo mx-auto w-md-100 w-lg-75 w-10" src="{% static 'img/facebook-gray-logo.svg' %}" alt="Representable's Facebook page linked from Facebook logo"></img></a>
        </div>
        <div class="col-md-1 text-center py-2 py-md-0">
          <a href="https://www.instagram.com/representable_org/" target="_blank"><img class="social-media-logo mx-auto w-md-100 w-lg-75 w-10" src="{% static 'img/ig-gray-logo.svg' %}" alt="Representable's Instagram page linked from Instagram logo"></img></a>
        </div>
        <div class="col-md-1 text-center py-2 py-md-0">
          <a href="https://twitter.com/representable_" target="_blank"><img class="social-media-logo mx-auto w-md-100 w-lg-75 w-10" src="{% static 'img/twitter-gray-logo.svg' %}" alt="Representable's Twitter page linked from Twitter logo"></img></a>
        </div>
        <div class="col-md-1 text-center py-2 py-md-0">
          <a href="https://www.youtube.com/channel/UCxDe9nogUoC37lAGfoC5ZRw" target="_blank"><img class="social-media-logo mx-auto w-md-100 w-lg-75 w-10" src="{% static 'img/yt-gray-logo.svg' %}" alt="Representable's Youtube page linked from Youtube logo"></img></a>
        </div>
        <div class="col-md-4"></div>
        <div class="text-center mx-auto mt-5">
          <a id="get-started-btn" class="text-center font-medium-mobile btn btn-outline-primary btn-lg py-3 btn-ls-lg mb-5 mt-2 border-solid" style="border-radius: 0;" href="{% url 'main:state_selection' %}"  role="button">{% trans "GET STARTED" %}</a>
        </div>
      </div>
    </div>
  </div>
  <div class="row w-100 m-0 light-blue-bg text-center">
    <div class="container">
      <div class="row pt-4">
        <div class="col-md-3"></div>
        <div class="col-md-6 text-center">
          <h3 class="font-medium-mobile btn-ls-lg pt-4 font-weight-bold">OUR PARTNERS</h3>
          <!-- image of partner organization logos -->
          <img class="card-img-top img-fluid m-2 mx-auto mb-md-4" src="{% static 'img/partner-logos.png' %}" alt="logos of organizations that partner with representable"></img>
        </div>
        <div class="col-md-3"></div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row pt-5">
      <img class="card-img-top w-62 mt-2 mx-auto mb-0" src="{% static 'img/home-hands.svg' %}" alt="hands holding shapes"></img>
    </div>
  </div>
{% endblock %}

{% block script %}
<script type="text/javascript">
  // Track Front Page Buttons
  document.getElementById("get-started-btn").addEventListener("click", function() {
      mixpanel.track("Get Started Pressed");
  });

  mixpanel.track_links("#edu-guide-link", "Educational Guide Link");
  mixpanel.track_links("#card-add-community-btn", "Card Add Community Click");
  mixpanel.track_links("#edu-guide-link-btn", "Card Partner Click");
  mixpanel.track_links("#hero-partner-btn", "Hero Partner With Us Click");
  mixpanel.track("Front Page Loaded");
</script>
{% endblock %}