main/urls.py
#
# Copyright (c) 2019- Representable Team (Theodor Marcu, Lauren Johnston, Somya Arora, Kyle Barnes, Preeti Iyer).
#
# This file is part of Representable
# (see http://representable.org).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
from django.urls import include, path

from main.views import main, partners, dashboard, drives
from main.views.dashboard import AllowListUpdate, AllowListManage, AllowListDelete
from representable.settings.base import MAPBOX_KEY

app_name = "main"
urlpatterns = [
    
    path(
        "accounts/login/",
        main.RepresentableLoginView.as_view(),
        name="account_login",
    ),
    path(
        "accounts/signup/",
        main.RepresentableSignupView.as_view(),
        name="account_signup",
    ),

    # google code comment
    # path(
    #     "accounts/social/signup/",
    #     views.main.RepresentableSocialSignupView.as_view(),
    #     name="socialaccount_signup",
    # ),

    path(
        'block_group_polygons/<str:abbr>/',
        main.block_group_polygons,
        name='block_group_polygons',
    ),
    path("", main.Index.as_view(), name="index"),
    path(
        "entry_preview/",
        main.StateSelection.as_view(),
        name="entry_preview",
    ),
    path(
        "state_selection/",
        main.StateSelection.as_view(),
        name="state_selection",
    ),
    path(
        "state_selection/map",
        main.StateSelection.as_view(),
        name="state_selection_map",
    ),
    path(
        "entry/",
        main.EntryView.as_view(),
        {"token": "", "drive": ""},
        name="entry",
    ),
    path(
        "entry/drive/<slug:drive>/",
        main.EntryView.as_view(),
        {"token": "", "abbr": ""},
        name="entry",  # deprecated? every drive page should redirect to incl. abbr
    ),
    path(
        "entry/drive/<slug:drive>/<abbr>",
        main.EntryView.as_view(),
        {"token": ""},
        name="entry",
    ),
    path(
        "entry/c/<slug:drive>/",
        main.EntryView.as_view(),
        {"token": ""},
        name="entry_legacy",  # for old links
    ),
    path(
        "entry/t/<token>/",
        main.EntryView.as_view(),
        {"drive": ""},
        name="entry",
    ),
    path(
        "entry/t/<token>/<abbr>/",
        main.EntryView.as_view(),
        {"drive": ""},
        name="entry",
    ),
    path(
        "entry/<abbr>/",
        main.EntryView.as_view(),
        {"token": "", "state": "", "drive": ""},
        name="entry",
    ),
    path("about/", main.About.as_view(), name="about"),
    path("faq/", main.FAQ.as_view(), name="faq"),
    path("glossary/", main.Glossary.as_view(), name="glossary"),
    path("resources/", main.Resources.as_view(), name="resources"),
    path("resources/<abbr>/", main.Resources.as_view(), {"state": ""}, name="resources"),
    path("review/", main.Review.as_view(), name="review"),
    path("privacy/", main.Privacy.as_view(), name="privacy"),
    path("terms/", main.Terms.as_view(), name="terms"),
    path("state/<abbr>/", main.StatePage.as_view(), name="state"),
    path(
        "submission/<map_id>",
        main.Submission.as_view(),
        {"slug": "", "drive": ""},
        name="submission",
    ),
    path(
        "submission/<map_id>/<abbr>",
        main.Submission.as_view(),
        {"slug": "", "drive": ""},
        name="submission",
    ),
    path(
        "submission/thanks/<map_id>/<abbr>",
        main.Submission.as_view(),
        {"slug": "", "drive": ""},
        name="submission_thanks",
    ),
    path(
        "submission/thanks/drive/<slug:slug>/<slug:drive>/<map_id>",
        main.Submission.as_view(),
        name="submission_thanks",
    ),
    # path("blog/", views.main.Blog.as_view(), name="blog"),
    path("export/geojson/", main.ExportView.as_view(), name="export"),
    path("export/csv/", main.ExportView.as_view(), name="export"),
    path("export/geojson/<abbr>/", main.ExportView.as_view(), name="export"),
    path("export/csv/<abbr>/", main.ExportView.as_view(), name="export"),
    path(
        "multiexport/<abbr>/<type>/",
        main.MultiExportView.as_view(),
        name="multi_export",
    ),
    path(
        "multiexport/drive/<drive>/<type>/",
        partners.MultiExportView.as_view(),
        name="multi_export",
    ),
    path(
        "multiexport/org/<org>/<type>/",
        partners.MultiExportView.as_view(),
        name="multi_export",
    ),
    path("partners/", partners.IndexView.as_view(), name="partner_list"),
    path(
        "partners/welcome/",
        partners.WelcomeView.as_view(),
        name="partner_welcome",
    ),
    path(
        "partners/<slug:slug>/",
        partners.PartnerView.as_view(),
        name="partner_page",
    ),
    path("map/<state>/", main.Map.as_view(), name="map"),
    path("map/<state>/<lat>/<lng>", main.Map.as_view(), name="map"),
    path(
        "map/p/<slug:slug>/",
        partners.PartnerMap.as_view(),
        {"drive": ""},
        name="partner_map",
    ),
    path(
        "map/p/<slug:slug>/<slug:drive>/",
        partners.PartnerMap.as_view(),
        name="partner_map",
    ),
    path(
        "report/",
        partners.ReportView.as_view(),
        name="report_community",
    ),
    path(
        "drive/<slug:slug>/",
        drives.DriveView.as_view(),
        name="drive_page",
    ),
    # keeping this for now to maintain link to user testing campaign
    path(
        "c/<slug:slug>/",
        drives.DriveView.as_view(),
        name="drive_page_legacy",
    ),
    path("dashboard/", dashboard.IndexView.as_view(), name="dashboard"),
    path(
        "dashboard/entries/<int:pk>",
        dashboard.ViewEntry.as_view(),
        name="dash_entry_list",
    ),
    path(
        "dashboard/entries/<int:pk>",
        dashboard.ViewEntry.as_view(),
        name="dash_view_entry",
    ),
    path(
        "dashboard/entries/<int:pk>/delete/",
        dashboard.DeleteEntry.as_view(),
        name="dash_delete_entry",
    ),
    path(
        "dashboard/partners/create/",
        dashboard.CreateOrg.as_view(),
        name="create_org",
    ),
    path(
        "dashboard/partners/<slug:slug>-<int:pk>/",
        include(
            [
                path("", dashboard.HomeOrg.as_view(), name="home_org"),
                path(
                    "thanks/",
                    dashboard.ThanksOrg.as_view(),
                    name="thanks_org",
                ),
                path(
                    "edit/", dashboard.EditOrg.as_view(), name="edit_org"
                ),
                path(
                    "delete/",
                    dashboard.DeleteOrg.as_view(),
                    name="delete_org",
                ),
                path(
                    "members/",
                    dashboard.ManageOrg.as_view(),
                    name="manage_org",
                ),
                path(
                    "members/create",
                    dashboard.CreateMember.as_view(),
                    name="create_member",
                ),
                path(
                    "drives/create/",
                    dashboard.CreateDrive.as_view(),
                    name="create_drive",
                ),
                path(
                    "drives/<uuid:cam_pk>/",
                    dashboard.DriveHome.as_view(),
                    name="drive_home",
                ),
                path(
                    "drives/<uuid:cam_pk>/edit/",
                    dashboard.UpdateDrive.as_view(),
                    name="update_drive",
                ),
                path(
                    "drives/<uuid:cam_pk>/delete/",
                    dashboard.DeleteDrive.as_view(),
                    name="delete_drive",
                ),
                path(
                    "drives/<uuid:cam_pk>/upload-allowlist/",
                    AllowListUpdate.as_view(),
                    name="upload_allowlist",
                ),
                path(
                    "drives/<uuid:cam_pk>/manage-allowlist/",
                    AllowListManage.as_view(),
                    name="manage_allowlist",
                ),
                path(
                    "drives/<uuid:cam_pk>/manage-allowlist/delete/",
                    AllowListDelete.as_view(),
                    name="delete_allowlist",
                ),
            ]
        ),
    ),
]

main/views/drives.py
from ..models import (
    Drive,
    State,
    # Image
)
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

# from django.views.generic.detail import SingleObjectMixin
from django.views.generic import (
    ListView,
    DetailView,
)

# from django.shortcuts import render
# # from ..forms import ImageForm

class IndexView(ListView):
    model = Drive
    template_name = "main/drives/index.html"
    pk_url_kwarg = "cam_pk"


class DriveView(DetailView):
    model = Drive
    template_name = "main/drives/page.html"
    pk_url_kwarg = "cam_pk"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Get Drive State object
        drive_slug = self.kwargs["slug"]
        drive = Drive.objects.get(slug=drive_slug)
        if (State.objects.filter(abbr=drive.state)):
            context["state"] = State.objects.filter(abbr=drive.state)[0]
            context["page_type"] = "drive-page"
        return context


# def showimage(request):
#     lastimage= Image.objects.last()
#     imagefile= lastimage.imagefile

#     form= ImageForm(request.POST or None, request.FILES or None)
#     if form.is_valid():
#         form.save()
  
#     context= {'imagefile': imagefile,
#               'form': form
#               }   
      
#     return render(request, 'Blog/images.html', context)

main/templates/main/dashboard/drives/create.html
{% extends 'main/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load i18n %}

{% block content %}
<div class="container-fluid">
                <div>
                    {% if verified %}
                    <div class="row" style="margin: 5%">
                    <div id="left-side-of-page" class="col-sm-9 col-md-8 col-lg-7 mx-auto">
                    {% comment %} <h5 class="card-title text-center"> {% endcomment %}
                    <h3>
                        {% trans "Create a Drive" %}
                    </h3>
                    <p>
                        {% blocktrans %} With Representable, your organization can create a drive to collect community maps. 
                        Then, you can send out a link to your customized drive page. {% endblocktrans %}
                    </p>
                    <form role="form" id="CreateDrive" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <div id="regular-fields">
                                <h5 class="text-primary"> {% trans "Drive Introduction" %} </h5>
                                {% for field in form %}
                                    {% if "Require" in field.label_tag %}
                                        <div class="fieldWrapper">
                                        <div class="form-check form-check-inline">
                                            {{ field.label_tag }}
                                            {{ field|append_attr:"class:mx-2 my-2" }}
                                        </div>
                                        </div>
                                    {% else %}
                                    {% if "opt" not in field.auto_id %}
                                        <div class="fieldWrapper">
                                        {{ field.errors }}
                                        {{ field.label_tag }}
                                        {{ field|append_attr:"class:form-control survey-field my-2" }}
                                        {% if field.help_text %}
                                            <p class="help">{{ field.help_text|safe }}</p>
                                        {% endif %}
                                        </div>
                                    {% endif %}
                                    {% endif %}
                                {% endfor %}
                            </div>
                            {% if gov %}
                                <div id="optional-fields-toggle" class="form-toggle form-toggle-inline form-check-inline">
                                    <h5 class="text-primary" style="padding-right: 10px; padding-top: 4px;"> {% trans "Edit Redistricting Information" %} </h5>
                                    <label class="switch">
                                        <input type="checkbox" id="edit-info" onchange="toggleFields()">
                                        <span class="slider round"></span>
                                    </label>
                                </div>
                            {% endif %}
                            <div id="optional-fields">
                                {% for field in form %}
                                    {% if "opt" in field.auto_id %}
                                        <div class="fieldWrapper">
                                        {{ field.errors }}
                                        {{ field.label_tag }}
                                        {{ field|append_attr:"class:form-control survey-field my-2" }}
                                        {% if field.help_text %}
                                        <p class="help">{{ field.help_text|safe }}</p>
                                        {% endif %}
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                        <div style="display: inline-block; padding-bottom: 30px">
                          <p class="text-muted mx-2 pb-3">
                            If you would like to include a custom question for users to answer when submitting a community to this mapping drive, please send us a request
                            at <a href="mailto:team@representable.org">team@representable.org</a>.</p>
                          <button id="save" form="CreateDrive" type="submit" class="btn btn-primary" value="Submit">Submit</button>
                        </div>
                    </form>
                    {% endif %}
                    </div>
                    <div id="right-side-of-page" class="col-sm-9 col-md-6 col-lg-5 mx-auto">
                        <h5 class="text-muted mx-2 pb-3"> Customizable Landing Page </h5>
                        <p class="text-muted mx-2 pb-3"> When you send the link to your mapping drive, members will see this page first. 
                        Customize this page to include a title and description of your mapping drive. 
                        Additionally, if you are a state or local government, you can edit the redistricting information in the blue boxes. 
                        </p>
                        <img width="100%" src="{% static 'img/drive_preview.png' %}" alt="Preview of drive page" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); margin-bottom: 20px;"> </img>
                    </div>
                    </div>
                    {% if not verified %}
                    <h5 class="card-title text-center">
                        Create a Drive
                    </h5>

                    <p class = "text-center"> Please first verify your email. Email verification is necessary
                        to access this feature on Representable. </p>
                    <p class = "text-center"> We have resent an email verification link to your inbox. Please don't
                    hesitate to reach out to us at team@representable.org with any questions.
                    </p>
                    {% endif %}

                </div>        
</div>
{% endblock %}
{% block script %}
<script type="text/javascript" src="{% static 'main/js/drive.js' %}"></script>
{% endblock %}

main/templates/main/dashboard/drives/edit.html
{% extends 'main/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">
                        Update your Drive
                      </h5>
                      <form role="form" id="UpdateDrive" method="post">{% csrf_token %}

                          <div class="form-group">
                        {% for field in form %}
                            {% if "require_user_addresses" in field.label_tag %}
                                        <div class="fieldWrapper">
                                        <div class="form-check form-check-inline">
                                            {{ field.label_tag }}
                                            {{ field }}
                                        </div>
                                        </div>
                                    {% else %}
                            {% if "opt" not in field.auto_id %}
                                <div class="fieldWrapper">
                                    {{ field.errors }}
                                    {{ field.label_tag }} {{ field|append_attr:"class:form-control survey-field" }}
                                    {% if field.help_text %}
                                    <p class="help">{{ field.help_text|safe }}</p>
                                    {% endif %}
                                </div>
                            {% endif %}
                            {% endif %}
                      {% endfor %}
                      </div>
                      <div style="display: inline-block;">
                          <button id="save" form="UpdateDrive" type="submit" class="btn btn-primary" value="Submit">Submit</button>
                      </div>
                      </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/dashboard/drives/index.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<script type="text/javascript" src="{% static 'main/js/base.js' %}"></script>
<div class="container-fluid light-blue-bg py-3">
  <div class="row">
    <div class="col-md-1 col-lg-2"></div>
    <div class="col-12 col-md-10 col-lg-8">
      <div class="row pt-3">
        <div class="col">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'main:home_org' object.organization.slug  object.organization.pk %}"><i class="fa fa-arrow-circle-left"></i> Return to {{ object.organization.name }}</a></li>
            </ol>
          </nav>
        </div>
      </div>
      <div class="row pt-3">
        <div class="col-sm">
          <div class="card border-0 shadow-sm h-100">
            <div class="card-body">
              <h4>
                {{ object.name}}
              </h4>
              {% if object.private %}
              <span class="badge badge-primary">{% trans "Private Drive" %}</span>
              {% endif %}
              <div class="mt-2">
                <p class="blue-text"><strong>{% trans "State" %}</strong>:
                  <span class="badge badge-secondary">{{object.state}}</span>
                </p>
              </div>
              <p class="scrollable"><strong class="blue-text">{% trans "Description" %}:</strong> {{ object.description }}</p>
              {% if object.require_user_addresses %}
              <p class="blue-text">{% trans "This drive requires street addresses." %}</p>
              {% endif %}

              <div class="row">
                <div class="col-6">
                  <a href="{% url 'main:update_drive' object.organization.slug  object.organization.pk object.pk %}" class="btn btn-primary btn-ls-md" role="button">{% trans "EDIT DETAILS" %}</a>
                </div>
                <div class="col-6">
                  {% if is_org_admin %}
                  <button class="btn btn-danger float-right btn-ls-md" data-toggle="modal" data-target="#deleteDriveConfirm">{% trans "DELETE" %}</button>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row pb-3">
        <div class="col-12 col-lg-6">
          <div class="card h-100 border-0 shadow-sm my-3 rounded-lg">
            <div class="card-body">
              <h6 class="text-primary text-xl-center py-2"><strong>{% trans "1. Gather Submissions" %}</strong></h6>
              <div class="row pb-2">
                <div class="d-none d-xl-block col-xl-2 pt-xl-1 text-right">
                  <i class="fas fa-home org-icon text-2A94F4"></i>
                </div>
                <div class="col-12 col-xl-10 pl-xl-2">

                  {% trans "Gather submissions for this drive! Share this link with people you'd like to contribute" %}: <a href="{% url 'main:drive_page' object.slug %}">representable.org{% url 'main:drive_page' object.slug %}</a>
                </div>
              </div>
              <div class="text-center org-card-btn">
                <button class="btn btn-primary btn-ls-md" role="button" onclick="copyLinkToClipboard('https://representable.org{% url 'main:drive_page' object.slug %}')">{% trans "COPY LINK" %}</button>

              </div>
            </div>
          </div>
        </div>
        <div class="col-12 col-lg-6 mt-3 mt-lg-0">
          <div class="card h-100 border-0 shadow-sm my-3 rounded-lg">
            <div class="card-body">
              <h6 class="text-primary text-xl-center py-2">
                {% if not object.private %}
                  <strong>
                  {% trans "2. View And Share Your Drive." %}
                  </strong>
                {% else %}
                  <strong>
                  {% trans "2. View Your Drive." %}
                  </strong>
                {% endif %}
              </h6>
              <div class="row pb-2">
                <div class="d-none d-xl-block col-xl-2 pt-xl-1 text-right">
                  <i class="fas fa-share-square org-icon text-2A94F4"></i>
                </div>
                <div class="col-12 col-xl-10 pl-xl-2">
                  {% comment %} {% trans "Gather submissions for this drive! Share this link with people you'd like to contribute" %}: <a href="{% url 'main:partner_map' object.slug %}">https://representable.org{% url 'main:partner_map' object.slug %}</a>  {% endcomment %}
                  {% if not object.private %}
                    <p>Your drive's map is live at: <a href="{% url 'main:partner_map' object.organization.slug object.slug %}">representable.org{% url 'main:partner_map' object.organization.slug object.slug %}</a></p>
                  {% endif %}
                  {% if object.private %}
                    <p>Your drive's map is available to organization administrators at: <a href="{% url 'main:partner_map' object.organization.slug object.slug %}">representable.org{% url 'main:partner_map' object.organization.slug object.slug %}</a></p>
                    <div>
                      <p>Only users you invite can submit to or see your private drive. Manage the invite list <a href="{% url 'main:manage_allowlist' object.organization.slug  object.organization.pk object.pk %}">here.</a><p>
                    </div>
                  {% endif %}
                </div>
              </div>
              <div class="text-center org-card-btn">
                <a class="btn btn-primary btn-ls-md" href="{% url 'main:partner_map' object.organization.slug object.slug %}"  role="button">VIEW MAPS</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% comment %} <div class="row">
        <div class="col-sm">
          <div class="card shadow-sm my-3">
            <div class="card-body">
              <h5>{% trans "Getting Started" %}</h5>
              <ul class="list-group my-3">
              {% if not object.private %}

                <li class="list-group-item d-flex justify-content-between align-items-center">
                  <div class="container pl-0 pr-0">
                    <h5><span class="badge badge-secondary"><i class="fas fa-share-alt"></i></span> Gather Submissions</h5>
                    <div class="row no-gutters">
                      <div class="col-9">
                        <p>Gather submissions for this drive! Copy this link and share it with people you'd like to contribute to this drive: <a href="{% url 'main:drive_page' object.slug %}">representable.org{% url 'main:drive_page' object.slug %}</a></p>
                      </div>
                      <div class="col">
                        <a class="btn btn-primary float-right" href="{% url 'main:drive_page' object.slug %}" role="button">View <i class="fa fa-arrow-circle-right"></i></a>
                      </div>
                    </div>
                  </div>
                </li>
              {% endif %}

                {% if object.private %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  <div>
                    <h5><span class="badge badge-secondary"><i class="fas fa-file-upload"></i></span> Manage Invite List </h5>
                    <p>Only users you invite can submit to or see your private drive. Manage the invite list here. <p>
                  </div>
                  <a class="btn btn-primary" href="{% url 'main:manage_allowlist' object.organization.slug  object.organization.pk object.pk %}" role="button">Manage <i class="fa fa-arrow-circle-right"></i></a>
                </li>
                {% endif %}

                <li class="list-group-item d-flex justify-content-between align-items-center">
                  <div class="container pl-0 pr-0">
                    <h5><span class="badge badge-secondary"><i class="fas fa-map-marker-alt"></i></span> View{% if not object.private %}/Share {% endif %} Your Map</h5>
                    <div class="row no-gutters">
                      <div class="col-9">
                      {% if not object.private %}
                        <p>Your drive's map is live at: <a href="{% url 'main:partner_map' object.organization.slug object.slug %}">representable.org{% url 'main:partner_map' object.organization.slug object.slug %}</a></p>
                      {% endif %}
                      {% if object.private %}
                        <p>Your drive's map is available to organization administrators at: <a href="{% url 'main:partner_map' object.organization.slug object.slug %}">representable.org{% url 'main:partner_map' object.organization.slug object.slug %}</a></p>
                      {% endif %}
                      </div>

                      <div class="col">
                        <a class="btn btn-primary float-right" href="{% url 'main:partner_map' object.organization.slug object.slug %}"  role="button">View <i class="fa fa-arrow-circle-right"></i></a>
                      </div>
                    </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div> {% endcomment %}
    </div>
    <div class="col-md-1 col-lg-2"></div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="deleteDriveConfirm" tabindex="-1" role="dialog" aria-labelledby="deleteDriveLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete this drive?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        This action cannot be undone. All drive information will be permanently deleted. Communities
        submitted through this drive will not be deleted, but will no longer be associated with the drive. These communities will still
        be associated with your organization.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form role="form" id="deleteDriveInfo" method="post" action="delete\">{% csrf_token %}
          {% comment %} <input type="hidden" name="drive_slug" value="{{ object.slug }}"> {% endcomment %}
          <button type="submit" class="btn btn-danger" name="Delete">Delete drive permanently</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}